/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './vacations.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/vacations/vacations.component';
const styles_VacationsComponent:any[] = [i0.styles];
export const RenderType_VacationsComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_VacationsComponent,data:{}});
export function View_VacationsComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  vacations works!\n'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_VacationsComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-vacations',
      ([] as any[]),(null as any),(null as any),(null as any),View_VacationsComponent_0,
      RenderType_VacationsComponent)),i1.ɵdid(114688,(null as any),0,i2.VacationsComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const VacationsComponentNgFactory:i1.ComponentFactory<i2.VacationsComponent> = i1.ɵccf('app-vacations',
    i2.VacationsComponent,View_VacationsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMva2JydW5zL2dpdGh1Yl9yZXBvcy9FU0xfdmFjYXRpb25zL3NyYy9hcHAvdmFjYXRpb25zL3ZhY2F0aW9ucy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMva2JydW5zL2dpdGh1Yl9yZXBvcy9FU0xfdmFjYXRpb25zL3NyYy9hcHAvdmFjYXRpb25zL3ZhY2F0aW9ucy5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9rYnJ1bnMvZ2l0aHViX3JlcG9zL0VTTF92YWNhdGlvbnMvc3JjL2FwcC92YWNhdGlvbnMvdmFjYXRpb25zLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMva2JydW5zL2dpdGh1Yl9yZXBvcy9FU0xfdmFjYXRpb25zL3NyYy9hcHAvdmFjYXRpb25zL3ZhY2F0aW9ucy5jb21wb25lbnQudHMuVmFjYXRpb25zQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XHJcbiAgdmFjYXRpb25zIHdvcmtzIVxyXG48L3A+XHJcbiIsIjxhcHAtdmFjYXRpb25zPjwvYXBwLXZhY2F0aW9ucz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLDRDQUVDO01BQUE7OztvQkNGSjtNQUFBO21DQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
