/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './msg.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from '../../../../src/app/msg/msg.component';
import * as i4 from '../../../../src/app/msg/msg.service';
const styles_MsgComponent:any[] = [i0.styles];
export const RenderType_MsgComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_MsgComponent,
    data:{}});
function View_MsgComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),7,'div',([] as any[]),
      [[8,'className',0]],(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'a',[['aria-label','close'],['class','close'],['data-dismiss','alert'],
              ['href','#']],(null as any),[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:any = _v.component;
            if (('click' === en)) {
              const pd_0:any = ((<any>_co.oncloseMsg()) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['×'])),(_l()(),
          i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'strong',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['',''])),(_l()(),i1.ɵted((null as any),
          [' ','\n']))],(null as any),(_ck,_v) => {
    var _co:any = _v.component;
    const currVal_0:any = i1.ɵinlineInterpolate(1,'alert alert-',_co.message.type,
        '');
    _ck(_v,0,0,currVal_0);
    const currVal_1:any = _co.message.title;
    _ck(_v,6,0,currVal_1);
    const currVal_2:any = _co.message.text;
    _ck(_v,7,0,currVal_2);
  });
}
export function View_MsgComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵand(16777216,(null as any),(null as any),1,(null as any),
      View_MsgComponent_1)),i1.ɵdid(16384,(null as any),0,i2.NgIf,[i1.ViewContainerRef,
      i1.TemplateRef],{ngIf:[0,'ngIf']},(null as any)),(_l()(),i1.ɵted((null as any),
      ['\n\n']))],(_ck,_v) => {
    var _co:i3.MsgComponent = _v.component;
    const currVal_0:any = _co.message;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_MsgComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-msg',([] as any[]),
      (null as any),(null as any),(null as any),View_MsgComponent_0,RenderType_MsgComponent)),
      i1.ɵdid(180224,(null as any),0,i3.MsgComponent,[i4.MsgService],(null as any),
          (null as any))],(null as any),(null as any));
}
export const MsgComponentNgFactory:i1.ComponentFactory<i3.MsgComponent> = i1.ɵccf('app-msg',
    i3.MsgComponent,View_MsgComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMva2JydW5zL2dpdGh1Yl9yZXBvcy9FU0xfdmFjYXRpb25zL3NyYy9hcHAvbXNnL21zZy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMva2JydW5zL2dpdGh1Yl9yZXBvcy9FU0xfdmFjYXRpb25zL3NyYy9hcHAvbXNnL21zZy5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9rYnJ1bnMvZ2l0aHViX3JlcG9zL0VTTF92YWNhdGlvbnMvc3JjL2FwcC9tc2cvbXNnLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMva2JydW5zL2dpdGh1Yl9yZXBvcy9FU0xfdmFjYXRpb25zL3NyYy9hcHAvbXNnL21zZy5jb21wb25lbnQudHMuTXNnQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImFsZXJ0IGFsZXJ0LXt7bWVzc2FnZS50eXBlfX1cIiAqbmdJZj1cIm1lc3NhZ2VcIj5cbiAgPGEgaHJlZj1cIiNcIiBjbGFzcz1cImNsb3NlXCIgZGF0YS1kaXNtaXNzPVwiYWxlcnRcIiBhcmlhLWxhYmVsPVwiY2xvc2VcIiAoY2xpY2spPVwib25jbG9zZU1zZygpXCI+JnRpbWVzOzwvYT5cbiAgPHN0cm9uZz57e21lc3NhZ2UudGl0bGV9fTwvc3Ryb25nPiB7e21lc3NhZ2UudGV4dH19XG48L2Rpdj5cblxuIiwiPGFwcC1tc2c+PC9hcHAtbXNnPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBMEQseUNBQ3hEO1VBQUE7Y0FBQTtZQUFBO1lBQUE7WUFBa0U7Y0FBQTtjQUFBO1lBQUE7WUFBbEU7VUFBQSxnQ0FBeUYsc0NBQVc7aUJBQUEsMEJBQ3BHO1VBQUE7VUFBQSxnQkFBUSx3Q0FBMEI7VUFBQTs7SUFGL0I7UUFBQTtJQUFMLFdBQUssU0FBTDtJQUVVO0lBQUE7SUFBMEI7SUFBQTs7OztvQkFGcEM7TUFBQSw2QkFBQTtvQkFBQSxtQ0FHTTtNQUFBOztJQUhvQztJQUExQyxXQUEwQyxTQUExQzs7OztvQkNBQTtNQUFBO2FBQUE7VUFBQTs7OyJ9
