/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app.module';
import * as i2 from '../../../src/app/app.component';
import * as i3 from '../../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as i4 from '../../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as i5 from '../../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as i6 from '../../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as i7 from '../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as i8 from '../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as i9 from '../../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as i10 from './dashboard/dashboard.component.ngfactory';
import * as i11 from './vacations/vacations.component.ngfactory';
import * as i12 from './vacations-add/vacations-add.component.ngfactory';
import * as i13 from './user-settings/user-settings.component.ngfactory';
import * as i14 from './app.component.ngfactory';
import * as i15 from '@angular/common';
import * as i16 from '@angular/platform-browser';
import * as i17 from '@angular/forms';
import * as i18 from 'angular-in-memory-web-api/in-memory-backend.service';
import * as i19 from '../../../src/app/datastore/user/user.datastore';
import * as i20 from '@angular/http';
import * as i21 from 'angular-in-memory-web-api/in-memory-web-api.module';
import * as i22 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as i23 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as i24 from '@ng-bootstrap/ng-bootstrap/alert/alert-config';
import * as i25 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar-config';
import * as i26 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip-config';
import * as i27 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead-config';
import * as i28 from '@ng-bootstrap/ng-bootstrap/accordion/accordion-config';
import * as i29 from '@ng-bootstrap/ng-bootstrap/carousel/carousel-config';
import * as i30 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-calendar';
import * as i31 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-i18n';
import * as i32 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-date-parser-formatter';
import * as i33 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-config';
import * as i34 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown-config';
import * as i35 from '@ng-bootstrap/ng-bootstrap/pagination/pagination-config';
import * as i36 from '@ng-bootstrap/ng-bootstrap/popover/popover-config';
import * as i37 from '@ng-bootstrap/ng-bootstrap/rating/rating-config';
import * as i38 from '@ng-bootstrap/ng-bootstrap/tabset/tabset-config';
import * as i39 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker-config';
import * as i40 from '@angular/router';
import * as i41 from '../../../src/app/datastore/user/user.service';
import * as i42 from '../../../src/app/msg/msg.service';
import * as i43 from '../../../src/app/app.config';
import * as i44 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as i45 from '@ng-bootstrap/ng-bootstrap/buttons/radio.module';
import * as i46 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as i47 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as i48 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as i49 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as i50 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as i51 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as i52 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as i53 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as i54 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as i55 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as i56 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as i57 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as i58 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as i59 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as i60 from '@ng-bootstrap/ng-bootstrap/index';
import * as i61 from '../../../src/app/dashboard/dashboard.component';
import * as i62 from '../../../src/app/vacations/vacations.component';
import * as i63 from '../../../src/app/vacations-add/vacations-add.component';
import * as i64 from '../../../src/app/user-settings/user-settings.component';
import * as i65 from '../../../src/app/app-routing.module';
import * as i66 from 'ng2-slimscroll/index';
import * as i67 from 'ng2-datepicker/lib-dist/ng2-datepicker.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.NgbAlertNgFactory,i4.NgbTooltipWindowNgFactory,i5.NgbTypeaheadWindowNgFactory,
              i6.NgbDatepickerNgFactory,i7.NgbModalBackdropNgFactory,i8.NgbModalWindowNgFactory,
              i9.NgbPopoverWindowNgFactory,i10.DashboardComponentNgFactory,i11.VacationsComponentNgFactory,
              i12.VacationsAddComponentNgFactory,i13.UserSettingsComponentNgFactory,
              i14.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i15.NgLocalization,
              i15.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,
              ([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i16.DomSanitizer,
              i16.ɵe,[i15.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i16.DomSanitizer]),
          i0.ɵmpd(4608,i16.HAMMER_GESTURE_CONFIG,i16.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i16.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i16.ɵDomEventsPlugin(p0_0),new i16.ɵKeyEventsPlugin(p1_0),
                new i16.ɵHammerGesturesPlugin(p2_0,p2_1)];
          },[i15.DOCUMENT,i15.DOCUMENT,i15.DOCUMENT,i16.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i16.EventManager,i16.EventManager,[i16.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i16.ɵDomSharedStylesHost,i16.ɵDomSharedStylesHost,[i15.DOCUMENT]),
          i0.ɵmpd(4608,i16.ɵDomRendererFactory2,i16.ɵDomRendererFactory2,[i16.EventManager,
              i16.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i16.ɵDomRendererFactory2]),i0.ɵmpd(6144,i16.ɵSharedStylesHost,(null as any),
              [i16.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i16.Meta,i16.Meta,[i15.DOCUMENT]),i0.ɵmpd(4608,
              i16.Title,i16.Title,[i15.DOCUMENT]),i0.ɵmpd(4608,i17.ɵi,i17.ɵi,([] as any[])),
          i0.ɵmpd(4608,i18.InMemoryDbService,i19.UserDataStore,([] as any[])),i0.ɵmpd(5120,
              i20.XHRBackend,i21.inMemoryBackendServiceFactory,[i0.Injector,i18.InMemoryDbService,
                  i18.InMemoryBackendConfig]),i0.ɵmpd(4608,i20.RequestOptions,i20.BaseRequestOptions,
              ([] as any[])),i0.ɵmpd(5120,i20.Http,i20.ɵc,[i20.XHRBackend,i20.RequestOptions]),
          i0.ɵmpd(4608,i20.BrowserXhr,i20.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i20.ResponseOptions,
              i20.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i20.XSRFStrategy,
              i20.ɵb,([] as any[])),i0.ɵmpd(4608,i22.NgbModalStack,i22.NgbModalStack,
              [i0.ApplicationRef,i0.Injector,i0.ComponentFactoryResolver]),i0.ɵmpd(4608,
              i23.NgbModal,i23.NgbModal,[i0.ComponentFactoryResolver,i0.Injector,i22.NgbModalStack]),
          i0.ɵmpd(4608,i24.NgbAlertConfig,i24.NgbAlertConfig,([] as any[])),i0.ɵmpd(4608,
              i25.NgbProgressbarConfig,i25.NgbProgressbarConfig,([] as any[])),i0.ɵmpd(4608,
              i26.NgbTooltipConfig,i26.NgbTooltipConfig,([] as any[])),i0.ɵmpd(4608,
              i27.NgbTypeaheadConfig,i27.NgbTypeaheadConfig,([] as any[])),i0.ɵmpd(4608,
              i28.NgbAccordionConfig,i28.NgbAccordionConfig,([] as any[])),i0.ɵmpd(4608,
              i29.NgbCarouselConfig,i29.NgbCarouselConfig,([] as any[])),i0.ɵmpd(4608,
              i30.NgbCalendar,i30.NgbCalendarGregorian,([] as any[])),i0.ɵmpd(4608,
              i31.NgbDatepickerI18n,i31.NgbDatepickerI18nDefault,([] as any[])),i0.ɵmpd(4608,
              i32.NgbDateParserFormatter,i32.NgbDateISOParserFormatter,([] as any[])),
          i0.ɵmpd(4608,i33.NgbDatepickerConfig,i33.NgbDatepickerConfig,([] as any[])),
          i0.ɵmpd(4608,i34.NgbDropdownConfig,i34.NgbDropdownConfig,([] as any[])),
          i0.ɵmpd(4608,i35.NgbPaginationConfig,i35.NgbPaginationConfig,([] as any[])),
          i0.ɵmpd(4608,i36.NgbPopoverConfig,i36.NgbPopoverConfig,([] as any[])),i0.ɵmpd(4608,
              i37.NgbRatingConfig,i37.NgbRatingConfig,([] as any[])),i0.ɵmpd(4608,
              i38.NgbTabsetConfig,i38.NgbTabsetConfig,([] as any[])),i0.ɵmpd(4608,
              i39.NgbTimepickerConfig,i39.NgbTimepickerConfig,([] as any[])),i0.ɵmpd(5120,
              i40.ActivatedRoute,i40.ɵf,[i40.Router]),i0.ɵmpd(4608,i40.NoPreloading,
              i40.NoPreloading,([] as any[])),i0.ɵmpd(6144,i40.PreloadingStrategy,
              (null as any),[i40.NoPreloading]),i0.ɵmpd(135680,i40.RouterPreloader,
              i40.RouterPreloader,[i40.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i40.PreloadingStrategy]),i0.ɵmpd(4608,i40.PreloadAllModules,
              i40.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i40.ROUTER_INITIALIZER,
              i40.ɵi,[i40.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i40.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i41.UserService,i41.UserService,
              [i20.Http]),i0.ɵmpd(4608,i42.MsgService,i42.MsgService,[i43.APP_CONFIG]),
          i0.ɵmpd(512,i15.CommonModule,i15.CommonModule,([] as any[])),i0.ɵmpd(1024,
              i0.ErrorHandler,i16.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,() => {
            return [i40.ɵb()];
          },([] as any[])),i0.ɵmpd(512,i40.ɵg,i40.ɵg,[i0.Injector]),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any,p1_0:any) => {
                return [i16.ɵc(p0_0,p0_1),i40.ɵh(p1_0)];
              },[[2,i16.NgProbeToken],[2,i0.NgProbeToken],i40.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i16.BrowserModule,i16.BrowserModule,[[3,i16.BrowserModule]]),
          i0.ɵmpd(512,i17.ɵba,i17.ɵba,([] as any[])),i0.ɵmpd(512,i17.FormsModule,i17.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i20.HttpModule,i20.HttpModule,([] as any[])),
          i0.ɵmpd(512,i21.InMemoryWebApiModule,i21.InMemoryWebApiModule,([] as any[])),
          i0.ɵmpd(512,i44.NgbAlertModule,i44.NgbAlertModule,([] as any[])),i0.ɵmpd(512,
              i45.NgbButtonsModule,i45.NgbButtonsModule,([] as any[])),i0.ɵmpd(512,
              i46.NgbCollapseModule,i46.NgbCollapseModule,([] as any[])),i0.ɵmpd(512,
              i47.NgbProgressbarModule,i47.NgbProgressbarModule,([] as any[])),i0.ɵmpd(512,
              i48.NgbTooltipModule,i48.NgbTooltipModule,([] as any[])),i0.ɵmpd(512,
              i49.NgbTypeaheadModule,i49.NgbTypeaheadModule,([] as any[])),i0.ɵmpd(512,
              i50.NgbAccordionModule,i50.NgbAccordionModule,([] as any[])),i0.ɵmpd(512,
              i51.NgbCarouselModule,i51.NgbCarouselModule,([] as any[])),i0.ɵmpd(512,
              i52.NgbDatepickerModule,i52.NgbDatepickerModule,([] as any[])),i0.ɵmpd(512,
              i53.NgbDropdownModule,i53.NgbDropdownModule,([] as any[])),i0.ɵmpd(512,
              i54.NgbModalModule,i54.NgbModalModule,([] as any[])),i0.ɵmpd(512,i55.NgbPaginationModule,
              i55.NgbPaginationModule,([] as any[])),i0.ɵmpd(512,i56.NgbPopoverModule,
              i56.NgbPopoverModule,([] as any[])),i0.ɵmpd(512,i57.NgbRatingModule,
              i57.NgbRatingModule,([] as any[])),i0.ɵmpd(512,i58.NgbTabsetModule,i58.NgbTabsetModule,
              ([] as any[])),i0.ɵmpd(512,i59.NgbTimepickerModule,i59.NgbTimepickerModule,
              ([] as any[])),i0.ɵmpd(512,i60.NgbRootModule,i60.NgbRootModule,([] as any[])),
          i0.ɵmpd(1024,i40.ɵa,i40.ɵd,[[3,i40.Router]]),i0.ɵmpd(512,i40.UrlSerializer,
              i40.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i40.ChildrenOutletContexts,
              i40.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i40.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i15.LocationStrategy,i40.ɵc,[i15.PlatformLocation,
              [2,i15.APP_BASE_HREF],i40.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i15.Location,
              i15.Location,[i15.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i40.ROUTES,
              () => {
                return [[{path:'',redirectTo:'/dashboard',pathMatch:'full'},{path:'dashboard',
                    component:i61.DashboardComponent},{path:'vacations',component:i62.VacationsComponent},
                    {path:'vacations/add',component:i63.VacationsAddComponent},{path:'user-settings',
                        component:i64.UserSettingsComponent}]];
              },([] as any[])),i0.ɵmpd(1024,i40.Router,i40.ɵe,[i0.ApplicationRef,i40.UrlSerializer,
              i40.ChildrenOutletContexts,i15.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i40.ROUTES,i40.ROUTER_CONFIGURATION,[2,i40.UrlHandlingStrategy],
              [2,i40.RouteReuseStrategy]]),i0.ɵmpd(512,i40.RouterModule,i40.RouterModule,
              [[2,i40.ɵa],[2,i40.Router]]),i0.ɵmpd(512,i65.AppRoutingModule,i65.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i66.SlimScrollModule,i66.SlimScrollModule,
              ([] as any[])),i0.ɵmpd(512,i67.DatePickerModule,i67.DatePickerModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[])),
          i0.ɵmpd(256,i18.InMemoryBackendConfig,(undefined as any),([] as any[])),
          i0.ɵmpd(256,i43.APP_CONFIG,i43.AppConfig,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMva2JydW5zL2dpdGh1Yl9yZXBvcy9FU0xfdmFjYXRpb25zL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9rYnJ1bnMvZ2l0aHViX3JlcG9zL0VTTF92YWNhdGlvbnMvc3JjL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
